### ISSUE TITLE
Your license is legally restrictive

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [wix/tspoon#103]
I'm looking into writing an open source auto-fixer for TSLint in line with [autopep8](https://github.com/hhatto/autopep8) (similar to [tsetse](https://github.com/alexeagle/tsetse)). Tspoon looks great but the following clause in your custom license could restrict any companies using it from being able to make a patent assertion against Wix:

>... If you (or any of your subsidiaries, corporate affiliates or agents) institute (either directly or indirectly), or gain a direct financial interest in, a Patent Assertion against
>  - Wix or any of its subsidiaries or corporate  affiliates,
>  - any person or entity, to the extent such Patent Assertion arises, in whole or in part, from any software, > technology, product or service of Wix or any of its subsidiaries or corporate affiliates, or
>  - any person or entity relating to the Software,
> 
> then the license granted herein shall automatically terminate without any notice...

Facebook's ReactJS had some similar wording in their license, which had some controversy. Could you speak on the matter?

**Comment by qballer** [comment]
What would you like to know?

**Comment by JoshuaKGoldberg** [comment]
> if you are in a patent dispute with it

"it" referring to Wix?

This is mostly a curiosity issue - I've seen a lot of hoopla about React licensing, and am curious whether adding a dependency on tspoon on a new OSS will restrict companies from adopting it.

*(if you just close this issue as irrelevant, that's ok too)*

**Comment by qballer** [comment]
> "it" referring to Wix?
Yes.

About what other companies will do, I don't know. I hope this package can still be useful for you.

**Comment by JoshuaKGoldberg** [comment]
LGTM
