### ISSUE TITLE
Ability to get back modified TypeScript code

### ISSUE THREAD

**Issue by mohsen1** [wix/tspoon#131]
TypeScript now has `ts.Printer` interface which allows you to emit TypeScript instead of JavaScript. It's going to be nice if spoon exposed an API in `TranspilerOutput` for getting back the TS code using `ts.Printer`

Note: This is a new feature in TypeScript 2.3

**Comment by AviVahl** [comment]
With TypeScript 2.3 introducing official transformation support, there might not be a need for `tspoon`...
See: https://github.com/Microsoft/TypeScript/pull/13940
