### ISSUE TITLE
Magic-string version update and change the magicString.overwrite usage

### ISSUE THREAD

**Issue by ismail-codar** [wix/tspoon#135]
I have a problem related to magic-sting. Please check https://github.com/Rich-Harris/magic-string/issues/120 

Currently fixed in my fork https://github.com/ismail-codar/tspoon/blob/master/src/mutable-source-code.ts#L28

**Comment by qballer** [comment]
Hello @ismail-codar, thanks for taking an interest in the project. We are aware there is an issue in this project that has to do with magic-string. Currently this project is being considered for deprecation. Please view [this](https://github.com/wix/tspoon/issues/136) issue for more details.
