### ISSUE TITLE
TSpoon is being considered for deprecation, please share your opinion.

### ISSUE THREAD

**Issue by qballer** [wix/tspoon#136]
Hello Guys, 

TSpoon was a solution for us in TypeScript 1.x, where the visitor capabilities were not where we wanted them to be. For people still using this version it could be a great solution. TypeScript 2 came a long and introduced a visitor API.  While this isn't documented yet, it can be found in [guides](http://blog.scottlogic.com/2017/05/02/typescript-compiler-api-revisited.html) online, and may be dugged up from code (e.g. [here](https://github.com/Microsoft/TypeScript/blob/9260a399a32ffde33c0e774dd5f129866c241ab2/src/compiler/visitor.ts)). 

For people still interested in this project, I wonder if there is a use case that makes this project still viable?

**Comment by ismail-codar** [comment]
I experienced some with typescript 2.5  and I make things easier with it rather than tspoon. The new transformation features are very cool. I think tspoon should deprecate.
